spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
    level:
      org:
        hibernate:
            SQL: debug
            type: trace
      root: debug