spring:
  application:
    name: backend
  profiles:
    active: local
    group:
      local:
        - common
        - local
        - secret
      prod:
        - common
        - prod
        - secret